title: WannabeOS Blog
description: i write stuff about wannabeOS project in here
url: "https://drewnobeton.github.io/wannabe-os/"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
collections:
  articles:
    output: true